### ISSUE TITLE
How to set page size? 

### ISSUE THREAD

**Issue by Antoniy2000** [Redth/Maui.VirtualListView#17]
When implement custom adapter there is only one method that download one item but I want to load few items at time

**Comment by Redth** [comment]
Take a look at the MusicDataAdapter sample: https://github.com/Redth/Maui.VirtualListView/blob/main/Sample/VirtualListViewSample/MusicDataAdapter.cs#L33
Notice how it caches all of the albums initially for performance.

You can pre-cache items in a similar way, in fact I do this in my own app (I pull the first 50 or so in the list, and then once I need to return an item that's not in that cache I pull the next 50 - though I could probably optimize this too and start pulling the next set in the background when I am asked to return say the 40th item from the existing cache) . 

The point with this pattern is that you can what's best for your scenario.

**Comment by Antoniy2000** [comment]
You just load all rows from db, but I have a large database with hundreds of rows, so it will be the best if adapter could load few rows a time asynchronously like devextreme datagrid does
