### ISSUE TITLE
Is there any way to implement async adapter?

### ISSUE THREAD

**Issue by Antoniy2000** [Redth/Maui.VirtualListView#18]
I want to use async functions to receive data from api/db

**Comment by Redth** [comment]
I don't imagine you'd want the adapter to be calling out to an API for the methods you're implementing - this would be rather slow.  Instead you should probably maintain a cache in your adapter which fills up the cache from the API in a separate task/thread so the adapter can quickly return items synchronously.

**Comment by Redth** [comment]
In any case, this is not something I'm planning on.  I believe you should be implementing async methods on your own adapter implementation to load and cache things when and as appropriate so that the adapter methods return quickly.
