### ISSUE TITLE
Adding Selection binding or event makes the list not displayed

### ISSUE THREAD

**Issue by eli191** [Redth/Maui.VirtualListView#20]
Hi,

I have the VirtualListView set up like this :

```
<vlv:VirtualListView
x:Name="vlv"
HorizontalOptions="FillAndExpand"
VerticalOptions="FillAndExpand"
BackgroundColor="White"
Adapter="{Binding Adapter}"
OnSelectedItemsChanged="vlv_SelectedItemsChanged"
SelectionMode="Single"
ItemTemplateSelector="{StaticResource ItemTemplateSelector}">

```
And in code behind

```
private void vlv_SelectedItemsChanged(object sender, SelectedItemsChangedEventArgs e)
{
if (e.NewSelection.Any())
{
var item = e.NewSelection.First();
vlv.ClearSelectedItems();
}
}
```

But the screen is white, the list doesn't show.

If I remove this line
`OnSelectedItemsChanged="vlv_SelectedItemsChanged"`
Then the list shows up fine.

If I change that line for a SelectedItem binding like this
`SelectedItem="{Binding SelectedItem}"`
Then, same thing happens, the list is not displayed on screen.

Do you have an idea of a workaround to get the selected item one way or the other ?

Thank you

**Comment by Redth** [comment]
Can you attach a full project reproducing the issue?

**Comment by tecno14** [comment]
I have similar issue, the list works fine for Windows, but hidden in Android, even without OnSelectedItemsChanged

**Comment by tecno14** [comment]
ok, I fixed the bug when I removed the <ScrollView> parent
