### ISSUE TITLE
OnScrolled Event not firing on iOS 17.3.1 device when I scroll the VLV content

### ISSUE THREAD

**Issue by tbaggett** [Redth/Maui.VirtualListView#33]
Hello, I've added an OnScrolled event handler to my VLV declaration in XAML, like so:

            <vlv:VirtualListView
                               Adapter="{Binding SettingsAdapter}"
                               OnScrolled="OnVirtualListViewScrolled"
                               BackgroundColor="Transparent"
                               Margin="8, 0" 
                               HorizontalOptions="FillAndExpand"
                               VerticalOptions="FillAndExpand" >

I added the method to the page code-behind like so:

    private void OnVirtualListViewScrolled(object? sender, ScrolledEventArgs e)
    {
        Console.WriteLine($"VLV Scroll Position: ScrollX = {e.ScrollX}, ScrollY = {e.ScrollY}");
    }

I set a breakpoint on the Console.WriteLine statement, then built/deployed to an iPhone SE running iOS 17.3.1, navigated to the page containing the VLV component and scrolled the content up and down. The breakpoint never gets hit.

Have I misunderstood the use of this event? Thanks!

**Comment by Vetle444** [comment]
Same here!
